# Generated by Django 5.1.4 on 2025-03-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="dimensions",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
    ]
