# Generated by Django 5.1.4 on 2025-03-30 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_remove_user_phone_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
