# Generated by Django 5.1.4 on 2025-03-29 06:53

import server.models.user_model
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("server", "0002_remove_product_dimensions_remove_product_sku"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="User",
        ),
        migrations.CreateModel(
            name="AdminStaff",
            fields=[],
            options={
                "verbose_name": "Admin User",
                "verbose_name_plural": "Admin Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("server.user",),
            managers=[
                ("objects", server.models.user_model.AdminManager()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("server.user",),
            managers=[
                ("objects", server.models.user_model.CustomerManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
