# Generated by Django 5.1.4 on 2025-03-29 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0003_rename_customer_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="reset_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="reset_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="token",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
