# Generated by Django 5.1.4 on 2025-03-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0004_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="DefaultBrand", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="connections",
            field=models.CharField(default="DefaultConnections", max_length=255),
        ),
    ]
