# Generated by Django 5.1.4 on 2025-03-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0005_product_brand_product_connections"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="DefaultType", max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
