name: Docker Build & Push (CD)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Tag Frontend Image
        run: |
          docker build -t kkhw/resonance-frontend:latest -f frontend/Dockerfile ./frontend
          docker tag kkhw/resonance-frontend:latest kkhw/resonance-frontend:${{ github.sha }}

      - name: Build & Tag Backend Image
        run: |
          docker build -t kkhw/resonance-backend:latest -f backend/Dockerfile ./backend
          docker tag kkhw/resonance-backend:latest kkhw/resonance-backend:${{ github.sha }}

      - name: Push Frontend Image
        run: |
          docker push kkhw/resonance-frontend:latest
          docker push kkhw/resonance-frontend:${{ github.sha }}

      - name: Push Backend Image
        run: |
          docker push kkhw/resonance-backend:latest
          docker push kkhw/resonance-backend:${{ github.sha }}
