# name: Docker Build & Push

# on:
#   push:
#     branches:
#       - main 

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build Docker Image
#         run: |
#           docker build -t kkhw/resonance-app:latest .
#           docker tag kkhw/resonance-app:latest kkhw/resonance-app:${{ github.sha }}

#       - name: Push Docker Image
#         run: |
#           docker push kkhw/resonance-app:latest
#           docker push kkhw/resonance-app:${{ github.sha }}
